import { Code2, Database, Wrench } from "lucide-react"

export const siteContent = {
  fr: {
    nav: [
      ["À propos", "about-me"],
      ["Projets", "projects"],
      ["Expérience", "experience"],
      ["Contact", "contact"],
    ],
    availability: "Disponible pour des opportunités",
    role: "Développeur Full-Stack · Support IT",
    location: "Toamasina I, Madagascar",
    heroHeading: "Votre expert pour les solutions informatiques",
    heroPortraitAlt: "Portrait illustré de Randrianarison Dieu Donné",
    hero: "Développeur et informaticien polyvalent, orienté support IT, assistance technique et solutions web utiles. Que ce soit pour concevoir des applications web, optimiser les performances ou résoudre des défis techniques complexes.",
    contactMe: "Me contacter",
    exploreWork: "Voir les projets",
    projectKicker: "Portfolio",
    projectTitle: "Découvrez ce que j'ai créé",
    projectDescription: "Chaque projet reflète ma passion pour l'innovation et mon engagement à livrer des résultats de haute qualité. Des produits utiles, du prototype au déploiement.",
    visitProject: "Visiter le projet",
    noPublicLink: "Lien public non communiqué",
    showMore: "Voir plus de projets",
    showLess: "Voir moins",
    projects: [
      {
        label: "Mémoire de Master",
        title: "EduSmart",
        url: "https://edusmart.site",
        description: "Plateforme intégrée de gouvernance scolaire et d’apprentissage adaptatif. Solution multi-tenant pour la gestion scolaire avec Next.js, Expo, Electron, Supabase, et IA (OpenRouter).",
        mark: "ES",
        image: "",
        icon: "education",
      },
      {
        label: "Projet personnel",
        title: "CareerFlow AI",
        url: "https://careerflow-ai-beta.vercel.app",
        description: "Plateforme SaaS no-code pour créer des CV et lettres de motivation. Intègre des templates modernes, l'export PDF, la sauvegarde cloud et un ATS Checker.",
        mark: "CF",
        image: "",
        icon: "resume",
      },
      {
        label: "Projet personnel",
        title: "Ny Baiboly DIEM v1.2",
        url: "https://github.com/dieudonne261/Ny-Baiboly-DIEM",
        description: "Application de lecture et d’étude de la Bible en malagasy. Offre une navigation fluide par livres et chapitres, avec une interface simple et une utilisation hors ligne.",
        mark: "NB",
        image: "/assets/images/diem.png",
        icon: "mobile",
      },
      {
        label: "Projet",
        title: "Lemurtrack",
        url: "",
        description: "Interface avec Fluent UI, React.js, Tailwind CSS, API et Electron.js.",
        mark: "LT",
        image: "/assets/images/lemurtrack.png",
        icon: "desktop",
      },
      {
        label: "Projet universitaire",
        title: "Suivi des étudiants",
        url: "",
        description: "Système de suivi académique avec tableau de bord interactif pour collecter, analyser et visualiser les données des étudiants.",
        mark: "SE",
        image: "/assets/images/suivie.png",
        icon: "analytics",
      },
      {
        label: "Projet web",
        title: "Web Services & API RESTful",
        url: "https://github.com/dieudonne261/TP-WebServ2023",
        description: "Projets concrets et exercices pratiques autour des technologies web et des APIs RESTful.",
        mark: "API",
        image: "/assets/images/REQUEST.gif",
        icon: "api",
      },
      {
        label: "Jeu web",
        title: "Chapel Main Game",
        url: "https://github.com/dieudonne261/Chapel-Main-Game",
        description: "Projet web utilisant npm, Express JS et MySQL.",
        mark: "CM",
        image: "/assets/images/Chapelle.jpg",
        icon: "game",
      },
      {
        label: "Design",
        title: "T-shirt Fampahafantarana LION",
        url: "https://dieudonne261.github.io/3D-View-T-shirts/",
        description: "Création du design de la promotion LION, inspiré par la force, la persévérance et le leadership.",
        mark: "LION",
        image: "/assets/images/lion.jpg",
        icon: "design",
      },
      {
        label: "Jeu web",
        title: "Tetris Game",
        url: "https://dieudonne261.github.io/tetris.github.io/",
        description: "Jeu web développé en JavaScript.",
        mark: "TR",
        image: "/assets/images/tetris.gif",
        icon: "game",
      },
      {
        label: "Tests d’application",
        title: "NetPro App",
        url: "",
        description: "Tests Android avec Postman, Python et tests JUnit / Espresso pour vérifier la connexion à une API sécurisée.",
        mark: "NP",
        image: "/assets/images/netproweb.png",
        icon: "app",
      },
    ],
    aboutKicker: "À propos",
    aboutTitle: "Développeur qui aime créer et accompagner",
    aboutText: "Bonjour ! Je suis Dieu Donné, titulaire d’un Master en Informatique, parcours Systèmes d’Information et Génie Logiciel. Je conçois des solutions web et accompagne les utilisateurs dans leur environnement informatique.\n\nAutonome, à l’écoute et orienté solutions, je veille à la qualité technique autant qu’à la clarté de l’expérience. Mon souci du détail me permet d'améliorer chaque interaction, garantissant non seulement la productivité mais aussi la satisfaction.",
    skillsLabel: "Compétences techniques",
    skills: [
      { title: "Langages", icon: Code2, values: ["Java", "C++", "C#", "PHP", "JavaScript"] },
      { title: "Web", icon: Code2, values: ["HTML", "CSS", "React.js", "Bootstrap 5", "Tailwind CSS", "Node.js", "Express.js", "Laravel"] },
      { title: "Données", icon: Database, values: ["MySQL", "PostgreSQL", "MongoDB"] },
      { title: "Outils & environnements", icon: Wrench, values: ["GitHub", "cPanel", "LWS", "Windows", "Linux", "MERISE", "UML"] },
    ],
    experienceKicker: "Expérience professionnelle",
    experienceTitle: "Mon parcours professionnel",
    experiences: [
      {
        role: "IT Personal Assistant",
        company: "STRELITZIA SCHOOL, Toamasina I",
        duration: "Fév 2026 - Août 2026",
        bullets: ["Support utilisateur et assistance technique (HelpDesk)", "Gestion des opérations de saisie de données"],
      },
      {
        role: "Stage Développeur Web",
        company: "Nexus SARLU, Toamasina I",
        duration: "Oct 2025 - Fév 2026",
        bullets: ["Intégration front-end dans le cadre de projets web collaboratifs", "Gestion du code source, suivi des versions et déploiement"],
      },
      {
        role: "IT et Formateur",
        company: "ONG Changes Of Madagascar, Toamasina I",
        duration: "Mars 2025 - Août 2025",
        bullets: ["Administration et maintenance du parc informatique", "Formation à Word, Excel, PowerPoint, Canva et usage d’Internet"],
      },
      {
        role: "Stage Développeur Web",
        company: "NetPro Web, Antsirabe I",
        duration: "Août 2023 - Nov 2023",
        bullets: ["Administration cPanel, hébergement de sites web et gestion des FTP", "Intégrations d’APIs et tests d’applications"],
      },
    ],
    educationKicker: "Éducation & certifications",
    educationTitle: "Mon parcours académique",
    education: [
      ["Master en Informatique", "Université Adventiste Zurcher, en ligne - Systèmes d’Information et Génie Logiciel - 2026"],
      ["Gemini & Google Certified Educator", "Google Edu - Utilisation pédagogique des outils Google - 2026"],
      ["Licence en Informatique", "Université Adventiste Zurcher, Antsirabe II - Systèmes d’Information et Génie Logiciel - 2024"],
      ["Formation Outils Bureautique", "ONG HELP Madagascar, Toamasina I - Word, Excel, PowerPoint et Internet - 2021"],
      ["Baccalauréat Scientifique (S)", "Lycée Jacques Rabemananjara, Toamasina I - 2021"],
    ],
    contactKicker: "Contact",
    contactTitle: "Parlons de votre prochain besoin numérique.",
    contactDescription: "Pour une question, une collaboration ou une mission, n'hésitez pas à me contacter. Je suis là pour vous aider !",
    writeEmail: "Écrire un e-mail",
    call: "Appeler / WhatsApp",
    contactForm: "Envoyer un message",
    name: "Votre nom",
    email: "Votre e-mail",
    message: "Votre message",
    send: "Ouvrir mon e-mail",
    formHint: "Votre client e-mail s’ouvrira avec votre message prérempli.",
    footer: "Conçu avec Next.js et des composants inspirés de shadcn/ui.",
    footerNavLabel: "Navigation",
    cvButton: "Télécharger mon CV",
    cvDialogTitle: "Quelle version du CV ?",
    cvDialogDescription: "Deux formats selon l'usage : lecture humaine ou dépôt sur une plateforme de recrutement.",
    cvProLabel: "CV professionnel",
    cvProDescription: "Mise en page soignée, à envoyer directement à un recruteur.",
    cvAtsLabel: "CV optimisé ATS",
    cvAtsDescription: "Version simplifiée, lisible par les logiciels de tri des candidatures.",
    cvUnavailable: "Bientôt disponible",
    aiTitle: "Assistant IA",
    aiSubtitle: "Posez une question sur le profil.",
    aiGreeting: "Bonjour ! Je peux vous renseigner sur les projets, compétences, expériences de Dieu Donné.",
    aiPlaceholder: "Écrivez votre question...",
    aiSuggestions: ["Quels sont ses projets ?", "Quelles sont ses compétences ?", "Comment le contacter ?"],
    aiFallback: "Je peux répondre aux questions sur les projets, les compétences, les expériences professionnelles, les formations ou le contact de Dieu Donné.",
  },
  en: {
    nav: [
      ["About", "about-me"],
      ["Projects", "projects"],
      ["Experience", "experience"],
      ["Contact", "contact"],
    ],
    availability: "Available for opportunities",
    role: "Full-Stack Developer · IT Support",
    location: "Toamasina I, Madagascar",
    heroHeading: "Your go-to IT expert & developer",
    heroPortraitAlt: "Illustrated portrait of Randrianarison Dieu Donné",
    hero: "A versatile developer and IT professional focused on IT support, technical assistance, and useful web solutions. Whether it's building web apps, optimizing performance, or solving complex technical challenges.",
    contactMe: "Contact me",
    exploreWork: "View projects",
    projectKicker: "Portfolio",
    projectTitle: "Discover what I've created",
    projectDescription: "Each piece reflects my passion for innovation and commitment to delivering high-quality results. Useful products, from prototype to deployment.",
    visitProject: "Visit project",
    noPublicLink: "No public link provided",
    showMore: "See more projects",
    showLess: "See fewer projects",
    projects: [
      {
        label: "Master’s thesis",
        title: "EduSmart",
        url: "https://edusmart.site",
        description: "An integrated platform for school governance and adaptive learning. Multi-tenant solution for school management with Next.js, Expo, Electron, Supabase, and AI (OpenRouter).",
        mark: "ES",
        image: "",
        icon: "education",
      },
      {
        label: "Personal project",
        title: "CareerFlow AI",
        url: "https://careerflow-ai-beta.vercel.app",
        description: "A SaaS no-code platform for creating CVs and cover letters. Includes modern templates, PDF export, cloud saving and an ATS Checker.",
        mark: "CF",
        image: "",
        icon: "resume",
      },
      {
        label: "Personal project",
        title: "Ny Baiboly DIEM v1.2",
        url: "https://github.com/dieudonne261/Ny-Baiboly-DIEM",
        description: "A Malagasy Bible reading and study application. Features fluid book and chapter navigation, a simple interface, and offline use.",
        mark: "NB",
        image: "/assets/images/diem.png",
        icon: "mobile",
      },
      {
        label: "Project",
        title: "Lemurtrack",
        url: "",
        description: "An interface built with Fluent UI, React.js, Tailwind CSS, API, and Electron.js.",
        mark: "LT",
        image: "/assets/images/lemurtrack.png",
        icon: "desktop",
      },
      {
        label: "University project",
        title: "Student Tracking",
        url: "",
        description: "An academic-tracking system with an interactive dashboard to collect, analyze, and visualize student data.",
        mark: "ST",
        image: "/assets/images/suivie.png",
        icon: "analytics",
      },
      {
        label: "Web project",
        title: "Web Services & RESTful API",
        url: "https://github.com/dieudonne261/TP-WebServ2023",
        description: "Practical projects and exercises around web technologies and RESTful APIs.",
        mark: "API",
        image: "/assets/images/REQUEST.gif",
        icon: "api",
      },
      {
        label: "Web game",
        title: "Chapel Main Game",
        url: "https://github.com/dieudonne261/Chapel-Main-Game",
        description: "A web project using npm, Express JS, and MySQL.",
        mark: "CM",
        image: "/assets/images/Chapelle.jpg",
        icon: "game",
      },
      {
        label: "Design",
        title: "LION promotional T-shirt",
        url: "https://dieudonne261.github.io/3D-View-T-shirts/",
        description: "A design for the LION class, inspired by strength, perseverance, and leadership.",
        mark: "LION",
        image: "/assets/images/lion.jpg",
        icon: "design",
      },
      {
        label: "Web game",
        title: "Tetris Game",
        url: "https://dieudonne261.github.io/tetris.github.io/",
        description: "A web game developed in JavaScript.",
        mark: "TR",
        image: "/assets/images/tetris.gif",
        icon: "game",
      },
      {
        label: "Application testing",
        title: "NetPro App",
        url: "",
        description: "Android testing with Postman, Python, and JUnit / Espresso to verify a secure API connection.",
        mark: "NP",
        image: "/assets/images/netproweb.png",
        icon: "app",
      },
    ],
    aboutKicker: "About",
    aboutTitle: "Developer who loves to build and support",
    aboutText: "Hello! I'm Dieu Donné, holding a Master’s degree in Computer Science, specializing in Information Systems and Software Engineering. I build web solutions and support users in their IT environments.\n\nAutonomous, attentive, and solution-oriented, I care deeply about technical quality and a clear experience. My attention to detail allows me to enhance every interaction, ensuring it boosts both productivity and user satisfaction.",
    skillsLabel: "Technical skills",
    skills: [
      { title: "Languages", icon: Code2, values: ["Java", "C++", "C#", "PHP", "JavaScript"] },
      { title: "Web", icon: Code2, values: ["HTML", "CSS", "React.js", "Bootstrap 5", "Tailwind CSS", "Node.js", "Express.js", "Laravel"] },
      { title: "Data", icon: Database, values: ["MySQL", "PostgreSQL", "MongoDB"] },
      { title: "Tools & environments", icon: Wrench, values: ["GitHub", "cPanel", "LWS", "Windows", "Linux", "MERISE", "UML"] },
    ],
    experienceKicker: "Professional experience",
    experienceTitle: "My professional journey",
    experiences: [
      {
        role: "IT Personal Assistant",
        company: "STRELITZIA SCHOOL, Toamasina I",
        duration: "Feb 2026 - Aug 2026",
        bullets: ["User support and technical assistance (HelpDesk)", "Data-entry operations management"],
      },
      {
        role: "Web Developer Intern",
        company: "Nexus SARLU, Toamasina I",
        duration: "Oct 2025 - Feb 2026",
        bullets: ["Front-end integration for collaborative web projects", "Source-code management, version tracking, and deployment"],
      },
      {
        role: "IT Specialist & Trainer",
        company: "ONG Changes Of Madagascar, Toamasina I",
        duration: "Mar 2025 - Aug 2025",
        bullets: ["IT infrastructure administration and maintenance", "Training in Word, Excel, PowerPoint, Canva, and Internet use"],
      },
      {
        role: "Web Developer Intern",
        company: "NetPro Web, Antsirabe I",
        duration: "Aug 2023 - Nov 2023",
        bullets: ["cPanel administration, website hosting, and FTP management", "API integrations and application testing"],
      },
    ],
    educationKicker: "Education & certifications",
    educationTitle: "My academic background",
    education: [
      ["Master’s in Computer Science", "Zurcher Adventist University, online - Information Systems and Software Engineering - 2026"],
      ["Gemini & Google Certified Educator", "Google Edu - Educational use of Google tools - 2026"],
      ["Bachelor’s in Computer Science", "Zurcher Adventist University, Antsirabe II - Information Systems and Software Engineering - 2024"],
      ["Office Tools Training", "ONG HELP Madagascar, Toamasina I - Word, Excel, PowerPoint, and Internet - 2021"],
      ["Baccalaureate (Science)", "Lycée Jacques Rabemananjara, Toamasina I - Science track (S) - 2021"],
    ],
    contactKicker: "Contact me",
    contactTitle: "Let's talk!",
    contactDescription: "For a question, collaboration, or role, the most direct way is to send me a message. I'm here to help!",
    writeEmail: "Write an email",
    call: "Call / WhatsApp",
    contactForm: "Send a message",
    name: "Your name",
    email: "Your email",
    message: "Your message",
    send: "Open my email",
    formHint: "Your email client will open with your message prefilled.",
    footer: "Built with Next.js and shadcn/ui-inspired components.",
    footerNavLabel: "Navigation",
    cvButton: "Download my resume",
    cvDialogTitle: "Which resume version?",
    cvDialogDescription: "Two formats depending on the use: human reading or applicant tracking systems.",
    cvProLabel: "Professional resume",
    cvProDescription: "Designed layout, ready to send straight to a recruiter.",
    cvAtsLabel: "ATS-friendly resume",
    cvAtsDescription: "Plain version, parsed reliably by recruitment software.",
    cvUnavailable: "Coming soon",
    aiTitle: "AI assistant",
    aiSubtitle: "Ask a question about the profile.",
    aiGreeting: "Hello! I can help with Dieu Donné’s projects, skills, experience, or contact details.",
    aiPlaceholder: "Write your question...",
    aiSuggestions: ["What are his projects?", "What are his skills?", "How can I contact him?"],
    aiFallback: "I can answer questions about Dieu Donné’s projects, skills, professional experience, education, or contact details.",
  },
} as const
